# data
data:
  eval_data: '' # Optional Fill
  shuffle: true
  train_data: '/home/administrator/workspace/moshi-finetune/manifest.jsonl' # Fill

# model
moshi_paths: 
  hf_repo_id: "kyutai/moshiko-pytorch-bf16"

full_finetuning: false # Activate lora.enable if partial finetuning
lora:
  enable: true # Set to False if full_finetuning is True
  rank: 128
  scaling: 2.
  ft_embed: false # Optional, set to True if you want to finetune the embedding layer

first_codebook_weight_multiplier: 100.
text_padding_weight: .5

# optim
duration_sec: 100
batch_size: 32
max_steps: 5000
gradient_checkpointing: true
optim:
  lr: 2e-6
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 100
do_eval: false
do_ckpt: true
ckpt_freq: 100
num_ckpt_keep: 4

save_adapters: true # Must be False if full_finetuning is True

overwrite_run_dir: true
run_dir: "/home/administrator/workspace/moshi-finetune/runs/ririka_v1"  # Fill

# This part is optional and can be kept commented out
wandb:
  project: "ririka-moshi" # your wandb project name
  run_name: "" # your wandb run name
  key: "04c8681fe30d07ab8440db48093171fe2365d3ef" # your wandb api key
  offline: False
